### ISSUE TITLE
Gamma filter ==> noll energi-deposition?

### ISSUE THREAD

**Issue by ghost** [MarielleAkser/Master_thesis#5]
https://github.com/MarielleAkser/Master_thesis/blob/1a25ee52cf73e7ac6aa06c41f038ea55e9ad126d/sauna/src/saunaDetectorConstruction.cc#L240

Gamma-partiklar lämnar aldrig energi "själva" utan det sker genom fotoelektrisk effekt eller Compton-spridning (eller parbildning) då elektroner bildas. De bildade elektronerna kommer sen att studsa runt i materialet och stanna och "lämnar av" sin energi på det sättet. Kanske är detta anledningen till att du inte få några hits i detektorn.

**Comment by MarielleAkser** [comment]
Testade, men ingen skillnad.

**Comment by ghost** [comment]
Jag ska försöka gräva lite. Vad skriver du på kommandoraden för att köra ditt program?

**Comment by MarielleAkser** [comment]
/control/execute gps.mac

**Comment by ghost** [comment]
Jag ökade antalet events i `/run/beamOn`, då hamnar exekveringen ibland i den inre loopen och skriver ut "In for-loop".
