### ISSUE TITLE
Mycket tunn cylinder

### ISSUE THREAD

**Issue by ghost** [MarielleAkser/Master_thesis#6]
https://github.com/MarielleAkser/Master_thesis/blob/a9da8747aa98948d441442fb2d328041e19ae37b/sauna/src/saunaDetectorConstruction.cc#L133

Med en inre radie som här så skapas ett cylindriskt "skal" vilket senare även blir din detektor. Det är ett tunt skal så väldigt lite fastnar däri. Den inre radien bör sättas till 0.0 cm för att få en cylinder med innehåll.

**Comment by MarielleAkser** [comment]
Ja, det känns ju vettigt.
